// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using bidtube.Domain.Data;

#nullable disable

namespace bidtube.Domain.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("bidtube.Domain.Entities.Auction", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("auction_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("category_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("date_of_auction")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("current_timestamp");

                    b.Property<DateTime>("date_of_expiration")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("current_timestamp");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("varchar(1024)");

                    b.Property<decimal>("startPrice")
                        .HasColumnType("decimal(20, 3)")
                        .HasColumnName("start_price");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("varchar(64)");

                    b.Property<int>("user_id")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("category_id");

                    b.HasIndex("user_id");

                    b.ToTable("auction", (string)null);
                });

            modelBuilder.Entity("bidtube.Domain.Entities.AuctionHistory", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("auction_history_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("auction_id")
                        .HasColumnType("int");

                    b.Property<int>("category_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("date_of_auction")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("current_timestamp");

                    b.Property<DateTime>("date_of_expiration")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("current_timestamp");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("varchar(1024)");

                    b.Property<decimal>("startPrice")
                        .HasColumnType("decimal(20, 3)")
                        .HasColumnName("start_price");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("varchar(64)");

                    b.Property<int?>("user_bought_id")
                        .HasColumnType("int");

                    b.Property<int>("user_id")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("category_id");

                    b.HasIndex("user_bought_id");

                    b.HasIndex("user_id");

                    b.ToTable("auction_history", (string)null);
                });

            modelBuilder.Entity("bidtube.Domain.Entities.AuctionImage", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("auction_image_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("alt_text")
                        .IsRequired()
                        .HasColumnType("varchar(96)");

                    b.Property<int>("auction_id")
                        .HasColumnType("int");

                    b.Property<string>("url")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("image_url");

                    b.HasKey("ID");

                    b.HasIndex("auction_id");

                    b.ToTable("auction_image", (string)null);
                });

            modelBuilder.Entity("bidtube.Domain.Entities.AuctionImageHistory", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("auction_image_history_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("alt_text")
                        .IsRequired()
                        .HasColumnType("varchar(96)");

                    b.Property<int>("auction_history_id")
                        .HasColumnType("int");

                    b.Property<int>("auction_id")
                        .HasColumnType("int");

                    b.Property<int>("auction_image_id")
                        .HasColumnType("int");

                    b.Property<string>("url")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("image_url");

                    b.HasKey("ID");

                    b.HasIndex("auction_history_id");

                    b.ToTable("auction_image_history", (string)null);
                });

            modelBuilder.Entity("bidtube.Domain.Entities.Bid", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("bid_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<decimal>("amount")
                        .HasColumnType("decimal(20, 3)");

                    b.Property<int>("auction_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("date_of_bid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("current_timestamp");

                    b.Property<int>("user_id")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("auction_id");

                    b.HasIndex("user_id");

                    b.ToTable("bid", (string)null);
                });

            modelBuilder.Entity("bidtube.Domain.Entities.BidHistory", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("bid_history_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<decimal>("amount")
                        .HasColumnType("decimal(20, 3)");

                    b.Property<int>("auction_history_id")
                        .HasColumnType("int");

                    b.Property<int>("auction_id")
                        .HasColumnType("int");

                    b.Property<int>("bid_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("date_of_bid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("current_timestamp");

                    b.Property<int>("user_id")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("auction_history_id");

                    b.HasIndex("user_id");

                    b.ToTable("bid_history", (string)null);
                });

            modelBuilder.Entity("bidtube.Domain.Entities.Category", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("category_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("icon_name")
                        .HasColumnType("varchar(64)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("varchar(64)");

                    b.Property<int?>("parent_category_id")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("parent_category_id");

                    b.ToTable("category", (string)null);
                });

            modelBuilder.Entity("bidtube.Domain.Entities.EventLog", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("event_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("error_code")
                        .HasColumnType("int");

                    b.Property<string>("error_message")
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime>("error_timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("current_timestamp");

                    b.HasKey("ID");

                    b.ToTable("event_log", (string)null);
                });

            modelBuilder.Entity("bidtube.Domain.Entities.Notification", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("notification_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("action")
                        .HasColumnType("varchar(15)");

                    b.Property<DateTime>("date_of_notification")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("current_timestamp");

                    b.Property<DateTime?>("date_of_read")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("current_timestamp");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("varchar(1024)");

                    b.Property<sbyte>("status")
                        .HasColumnType("tinyint");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("varchar(64)");

                    b.Property<int>("user_id")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("user_id");

                    b.ToTable("notification", (string)null);
                });

            modelBuilder.Entity("bidtube.Domain.Entities.Review", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("review_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("auction_history_id")
                        .HasColumnType("int");

                    b.Property<string>("comment")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("date_of_review")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("current_timestamp");

                    b.Property<sbyte>("rating")
                        .HasColumnType("tinyint");

                    b.Property<int>("received_id")
                        .HasColumnType("int");

                    b.Property<int>("sent_id")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("auction_history_id");

                    b.HasIndex("received_id");

                    b.HasIndex("sent_id");

                    b.ToTable("review", (string)null);
                });

            modelBuilder.Entity("bidtube.Domain.Entities.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime?>("date_of_birth")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("mail")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<ulong>("msg_allowed_from_anyone")
                        .HasColumnType("bit")
                        .HasColumnName("msg_allowed_from");

                    b.Property<byte[]>("password")
                        .IsRequired()
                        .HasColumnType("binary(60)");

                    b.Property<string>("phone")
                        .HasColumnType("varchar(25)");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("varchar(24)");

                    b.HasKey("ID");

                    b.ToTable("user", (string)null);
                });

            modelBuilder.Entity("bidtube.Domain.Entities.Auction", b =>
                {
                    b.HasOne("bidtube.Domain.Entities.Category", "Category")
                        .WithMany("Auctions")
                        .HasForeignKey("category_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("bidtube.Domain.Entities.User", "User")
                        .WithMany("Auctions")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("bidtube.Domain.Entities.AuctionHistory", b =>
                {
                    b.HasOne("bidtube.Domain.Entities.Category", "Category")
                        .WithMany("Auctions_history")
                        .HasForeignKey("category_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("bidtube.Domain.Entities.User", "Winner")
                        .WithMany("AuctionsWon")
                        .HasForeignKey("user_bought_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("bidtube.Domain.Entities.User", "User")
                        .WithMany("Auctions_history")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("User");

                    b.Navigation("Winner");
                });

            modelBuilder.Entity("bidtube.Domain.Entities.AuctionImage", b =>
                {
                    b.HasOne("bidtube.Domain.Entities.Auction", "Auction")
                        .WithMany("Images")
                        .HasForeignKey("auction_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Auction");
                });

            modelBuilder.Entity("bidtube.Domain.Entities.AuctionImageHistory", b =>
                {
                    b.HasOne("bidtube.Domain.Entities.AuctionHistory", "Auction")
                        .WithMany("Images")
                        .HasForeignKey("auction_history_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Auction");
                });

            modelBuilder.Entity("bidtube.Domain.Entities.Bid", b =>
                {
                    b.HasOne("bidtube.Domain.Entities.Auction", "Auction")
                        .WithMany("Bids")
                        .HasForeignKey("auction_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("bidtube.Domain.Entities.User", "User")
                        .WithMany("UserBids")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Auction");

                    b.Navigation("User");
                });

            modelBuilder.Entity("bidtube.Domain.Entities.BidHistory", b =>
                {
                    b.HasOne("bidtube.Domain.Entities.AuctionHistory", "Auction")
                        .WithMany("Bids")
                        .HasForeignKey("auction_history_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("bidtube.Domain.Entities.User", "User")
                        .WithMany("UserBids_history")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Auction");

                    b.Navigation("User");
                });

            modelBuilder.Entity("bidtube.Domain.Entities.Category", b =>
                {
                    b.HasOne("bidtube.Domain.Entities.Category", "Parent")
                        .WithMany("Subcategories")
                        .HasForeignKey("parent_category_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("bidtube.Domain.Entities.Notification", b =>
                {
                    b.HasOne("bidtube.Domain.Entities.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("bidtube.Domain.Entities.Review", b =>
                {
                    b.HasOne("bidtube.Domain.Entities.AuctionHistory", "Auction")
                        .WithMany("Reviews")
                        .HasForeignKey("auction_history_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("bidtube.Domain.Entities.User", "User")
                        .WithMany("ReviewsReceived")
                        .HasForeignKey("received_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("bidtube.Domain.Entities.User", "User_Sent")
                        .WithMany("ReviewsGiven")
                        .HasForeignKey("sent_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Auction");

                    b.Navigation("User");

                    b.Navigation("User_Sent");
                });

            modelBuilder.Entity("bidtube.Domain.Entities.Auction", b =>
                {
                    b.Navigation("Bids");

                    b.Navigation("Images");
                });

            modelBuilder.Entity("bidtube.Domain.Entities.AuctionHistory", b =>
                {
                    b.Navigation("Bids");

                    b.Navigation("Images");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("bidtube.Domain.Entities.Category", b =>
                {
                    b.Navigation("Auctions");

                    b.Navigation("Auctions_history");

                    b.Navigation("Subcategories");
                });

            modelBuilder.Entity("bidtube.Domain.Entities.User", b =>
                {
                    b.Navigation("Auctions");

                    b.Navigation("AuctionsWon");

                    b.Navigation("Auctions_history");

                    b.Navigation("Notifications");

                    b.Navigation("ReviewsGiven");

                    b.Navigation("ReviewsReceived");

                    b.Navigation("UserBids");

                    b.Navigation("UserBids_history");
                });
#pragma warning restore 612, 618
        }
    }
}
